### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by noraj** [maraudery/qualear#1]
Why does the tool constantly change of name ?

Omniscient -> RA -> Qualear

**Comment by maraudery** [comment]
Ah yes, I apologize. I ran into some conflict with some people regarding the name Omniscient. That caused me to switch to RA which I honestly just did not like in the slightest. Where it is now, at Qualear, is where it will stay.

**Comment by noraj** [comment]
Yay, Qualear way better than RA

**Comment by maraudery** [comment]
Glad you like it :)
